name: Person

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  details:
    runs-on: ubuntu-latest
    steps:
      - name: Manish 
      - role: DevOps Engineer
      - experience_year: 13 year
      - learning: true
      - hobbies: [travelling, fitness]
      - tools: 
          - Linux
          - Git/Github
          - Shell Script
          - Networking
          - Docker
