global:
  imageRegistry: docker.io
  security:
    allowInsecureImages: true

image:
  repository: bitnamilegacy/mysql

auth:
  rootPassword: Test@123
  database: bankappdb

primary:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  persistence:
    size: 5Gi
    storageClass: ""

metrics:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/mysqld-exporter
  serviceMonitor:
    enabled: false
