kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: day51-task-cluster

nodes:
- role: control-plane
  image: kindest/node:v1.35.0      #Docker image to make a node

- role: worker
  image: kindest/node:v1.35.0

