kind: Pod
apiVersion: v1
metadata:
  name: redis
  labels:
    app: redis
    environment: dev
    team: DevOps

spec:
  containers:
    - name: redis
      image: redis:latest
      ports:
        - containerPort: 6379