kind: Pod
apiVersion: v1

metadata:
  name: secret-pod

spec:
  containers:
    - name: secret-pod
      image: busybox:1.36
      command:
        ["/bin/sh", "-c", "echo 'This is buxybox container, Sleeping for 3600 second.'; sleep 3600"]
      env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credential-secret
              key: DB_USER
      volumeMounts:
        - name: db-credentials-volume
          mountPath: /etc/db-credentials
          readOnly: true


  volumes:
    - name: db-credentials-volume
      secret:
        secretName: db-credential-secret