kind: Service
apiVersion: v1

metadata:
  name: mysql-headless-service

spec:
  clusterIP: None  #this makes it headless service
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql