services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_pass
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
    networks:
      - mylearning-nw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pTest@123"]
      interval: 5s
      timeout: 5s
      retries: 20

  wordpress:
    image: wordpress:latest
    container_name: my-wordpress-container
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_pass
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - type: volume
        source: wordpress_data
        target: /var/www/html
    depends_on:
      - mysql
    networks:
      - mylearning-nw

networks:
  mylearning-nw:

volumes:
  mysql_data:
  wordpress_data:
