kind: Pod
apiVersion: V1

metadata:
  name: oomkilled-pod

spec:
  containers:
    - name: stress
      image: polinux/stress

      resources:
        requests:
          memory: 50Mi
        limits:
          memory: 100Mi
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "200M", "--vm-hang", "1"]