apiVersion: v1
kind: Pod

metadata:
  name: resource-pod
  labels:
    app: resource-pod

spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi