apiVersion: v1
kind: Pod
metadata:
  name: startup-probe-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "App starting..." &&
          sleep 20 &&
          touch /tmp/started &&
          echo "App started!" &&
          sleep 600

      startupProbe:
        exec:
          command: ["cat", "/tmp/started"]
        periodSeconds: 5        # check every 5s
        #failureThreshold: 12    # 12 x 5s = 60s budget for startup
                                # liveness is DISABLED until this passes
        failureThreshold: 2
      livenessProbe:
        exec:
          command: ["cat", "/tmp/started"]
        periodSeconds: 5
        failureThreshold: 3